/**
 * One RDS PostgreSQL instance holding one database per service.
 *
 * **Database-per-service is preserved; instance-per-service is not.** The platform rule is that
 * no service may read another's tables, and what enforces that here is the grant: each service
 * gets its own role, owning its own database, with `CONNECT` revoked on everyone else's. A
 * cross-service query fails with a permission error rather than returning rows. Six separate
 * instances would enforce the same thing with six times the bill, and the boundary that matters
 * is the one in the code, not the one in the hypervisor.
 *
 * Splitting later is a data migration, not a redesign: each service already talks to its own
 * `DB_URL`, so moving one database to its own instance changes one secret.
 *
 * ## The master password is not in Terraform state
 *
 * `manage_master_user_password` hands the master credential to RDS, which generates it, stores
 * it in Secrets Manager and rotates it. Terraform never sees the value, so it never lands in
 * the state file. The alternative - `random_password` for the master - puts an admin credential
 * for the whole platform in plain text in the state object for ever, including in every
 * historical version the bucket keeps.
 *
 * The per-service passwords below *are* generated by Terraform and therefore *are* in state.
 * That is a considered trade: they are scoped to one database each, and the alternative is
 * managing six credentials by hand with no record of which is current. It is also why the state
 * bucket is encrypted, versioned and blocked from public access - see `bootstrap/`.
 */

resource "aws_db_subnet_group" "this" {
  name        = "${var.name_prefix}-db"
  description = "Private subnets only - this database has no public endpoint"
  subnet_ids  = var.subnet_ids

  tags = merge(var.tags, { Name = "${var.name_prefix}-db" })
}

resource "aws_security_group" "database" {
  name        = "${var.name_prefix}-db"
  description = "PostgreSQL, from the application tasks only"
  vpc_id      = var.vpc_id

  tags = merge(var.tags, { Name = "${var.name_prefix}-db" })
}

resource "aws_vpc_security_group_ingress_rule" "from_services" {
  security_group_id            = aws_security_group.database.id
  description                  = "PostgreSQL from the six application tasks"
  referenced_security_group_id = var.service_security_group_id
  from_port                    = 5432
  to_port                      = 5432
  ip_protocol                  = "tcp"
}

resource "aws_db_parameter_group" "this" {
  name        = "${var.name_prefix}-pg16"
  family      = "postgres16"
  description = "Martensa PostgreSQL 16"

  # Log anything slower than a second. Not zero: logging every statement on a shared instance
  # is how the log bill overtakes the database bill, and the queries worth seeing are the slow
  # ones. One second is high enough to stay quiet and low enough that a missing index shows up.
  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }

  # Refuse unencrypted connections. Every service already sets sslmode in its JDBC URL; this is
  # the half that cannot be forgotten in a config file.
  parameter {
    name         = "rds.force_ssl"
    value        = "1"
    apply_method = "pending-reboot"
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = var.tags
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name_prefix}-postgres"
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = "gp3"
  storage_encrypted     = true

  # An initial database, so the instance has something to connect to. The per-service databases
  # are created by the SQL in the `bootstrap_sql` output, run once by hand - see that output and
  # docs/infrastructure.md for why Terraform cannot create them itself.
  db_name  = "martensa"
  username = "martensa_admin"

  # RDS generates, stores and rotates it. See the header: this is what keeps the platform's
  # admin credential out of the state file.
  manage_master_user_password = true

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.database.id]
  parameter_group_name   = aws_db_parameter_group.this.name

  # No public endpoint, ever. The security group already restricts the source, but a public
  # endpoint means the database answers a TCP handshake from the whole internet, and every
  # credential-stuffing bot finds it within hours.
  publicly_accessible = false

  multi_az = var.multi_az

  backup_retention_period = var.backup_retention_days
  # Outside Romanian business hours. RDS takes the snapshot against the storage layer, so it is
  # not the freeze it used to be, but a restore window nobody is awake for is still the right
  # default.
  backup_window      = "01:00-02:00"
  maintenance_window = "Sun:02:30-Sun:03:30"

  # Minor versions only. A major version upgrade rewrites the catalog and can break a query
  # plan; that belongs in a planned change with a tested rollback, not in a maintenance window.
  auto_minor_version_upgrade  = true
  allow_major_version_upgrade = false

  # `false` in production, and the variable defaults accordingly. Left as a variable because a
  # scratch environment that cannot be destroyed without clicking through a final-snapshot
  # prompt is an environment nobody tears down, which is how a $12-a-month instance runs for a
  # year.
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name_prefix}-postgres-final"
  deletion_protection       = var.deletion_protection

  # Postgres logs to CloudWatch. Without this the log file lives on the instance and is gone
  # with it - including the record of whatever made you destroy the instance.
  enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]

  # Free tier: seven days of per-second metrics. Enough to see a lock storm after the fact,
  # which the one-minute CloudWatch metrics smooth away entirely.
  performance_insights_enabled          = var.performance_insights_enabled
  performance_insights_retention_period = var.performance_insights_enabled ? 7 : null

  tags = merge(var.tags, { Name = "${var.name_prefix}-postgres" })
}

# ---------------------------------------------------------------------------
# Per-service credentials
# ---------------------------------------------------------------------------

# One password per service database. `special = false` because the value ends up inside a JDBC
# URL and in a shell environment variable: a `@` splits the URL at the host, a `$` is expanded
# by a shell, and both fail as an authentication error that names neither.
resource "random_password" "service" {
  for_each = var.service_databases

  length  = 32
  special = false
}

# The whole connection, not just the password. A service reads one secret and has everything -
# no template in a task definition assembling a URL from three sources, which is where a
# hostname change becomes six near-identical edits and one that got missed.
resource "aws_secretsmanager_secret" "service" {
  for_each = var.service_databases

  name        = "${var.name_prefix}/db/${each.key}"
  description = "PostgreSQL credentials for the ${each.key} service"

  # Zero, so `terraform destroy` followed by `terraform apply` works. Secrets Manager otherwise
  # keeps a deleted secret for 7-30 days and refuses to create one with the same name, which
  # turns a rebuild into a week's wait or a rename.
  recovery_window_in_days = var.secret_recovery_window_days

  tags = merge(var.tags, { Name = "${var.name_prefix}-db-${each.key}", Service = each.key })
}

resource "aws_secretsmanager_secret_version" "service" {
  for_each = var.service_databases

  secret_id = aws_secretsmanager_secret.service[each.key].id
  secret_string = jsonencode({
    username = each.value
    password = random_password.service[each.key].result
    # sslmode=require, matching rds.force_ssl above. A driver that does not ask for TLS is
    # refused by the server, and the error says "no pg_hba.conf entry" - which sends people to
    # look at network rules rather than at the connection string.
    url = "jdbc:postgresql://${aws_db_instance.this.address}:${aws_db_instance.this.port}/${each.key}?sslmode=require"
  })
}
