output "endpoint" {
  description = "host:port for the instance."
  value       = aws_db_instance.this.endpoint
}

output "address" {
  description = "Hostname only, for building a connection string by hand."
  value       = aws_db_instance.this.address
}

output "security_group_id" {
  description = "The database's security group, for adding a bastion or a migration task later."
  value       = aws_security_group.database.id
}

output "master_secret_arn" {
  description = <<-EOT
    The RDS-managed master credential in Secrets Manager.

    Needed to run the `bootstrap_sql` output below, which is the one step Terraform cannot do
    itself - see docs/infrastructure.md.
  EOT
  value       = aws_db_instance.this.master_user_secret[0].secret_arn
}

output "service_secret_arns" {
  description = "Per-service connection secrets, by database name. ECS task definitions reference these by ARN."
  value       = { for name, secret in aws_secretsmanager_secret.service : name => secret.arn }
}

output "bootstrap_sql" {
  description = <<-EOT
    The SQL that creates the per-service databases and roles, rendered with the generated
    passwords.

    Marked sensitive, so it is not printed by `terraform output` without asking. Read it with
    `terraform output -raw bootstrap_sql` and pipe it into psql through a port-forward.
  EOT
  sensitive   = true
  value = join("\n", concat(
    ["-- Generated by Terraform. Run once, against the instance's default 'martensa' database.",
    "-- Re-running is safe: every statement is guarded."],
    flatten([
      for name, role in var.service_databases : [
        "",
        "-- ${name}",
        "DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${role}') THEN CREATE ROLE ${role} LOGIN PASSWORD '${random_password.service[name].result}'; END IF; END $$;",
        "ALTER ROLE ${role} WITH PASSWORD '${random_password.service[name].result}';",
        "SELECT 'CREATE DATABASE ${name} OWNER ${role}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${name}')\\gexec",
        # The grant that makes database-per-service an enforced boundary rather than a
        # convention: without CONNECT, a service holding another service's credentials still
        # cannot open a session against the wrong database.
        "REVOKE CONNECT ON DATABASE ${name} FROM PUBLIC;",
        "GRANT CONNECT ON DATABASE ${name} TO ${role};",
      ]
    ])
  ))
}
